services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: itireland
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "6060:80"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo
    logging:
      options:
        max-size: 1g
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=itireland
#      - MONGO_INITDB_ROOT_PASSWORD=123
    image: mongo
    networks:
      - mongo
    volumes:
      - mongo:/data/mongo
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - spring
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.12.1-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
    restart: unless-stopped

#  eureka-server:
#    image: ypydd88/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#  apigw:
#    image: ypydd88/apigw-server:latest
#    container_name: apigw
#    ports:
#      - "8080:8080"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#
#  user:
#    image: ypydd88/user-service:latest
#    container_name: user
#    ports:
#      - "8083:8083"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - eureka-server
#      - zipkin
#  post:
#    image: ypydd88/post-service:latest
#    container_name: post
#    ports:
#      - "8081:8081"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    networks:
#      - spring
#      - mongo
#    depends_on:
#      - eureka-server
#      - zipkin
#  notification:
#    image: ypydd88/notification-service:latest
#    container_name: notification
#    ports:
#      - "8082:8082"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - eureka-server
#      - zipkin
#      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: