server:
    port: 8080

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://zipkin:9411
    cloud:
      gateway:
        routes:
          - id: user
            uri: lb://USER
            predicates:
              - Path=/api/v1/users/**
          - id: post
            uri: lb://POST
            predicates:
              - Path=/api/v1/posts/**

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"