server:
  port: 8080

spring:
  application:
    name: apigw

  zipkin:
    base-url: http://localhost:9411

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
        - id: post
          uri: lb://POST
          predicates:
            - Path=/api/v1/posts/**

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"