server:
  port: 8080

spring:
  application:
    name: apigw

  zipkin:
    base-url: http://localhost:9411

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
        - id: post
          uri: lb://POST
          predicates:
            - Path=/api/v1/posts/**,/api/v1/comments/**,/api/v1/tags/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
      ##允许请求跨域
      globalcors:
        add-to-simple-url-handler-mapping: true # 允许Options请求询问是否允许跨域
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://USER:8083"
              - "http://POST:8081"
              - "http://NOTIFICATION:8082"
              - "http://AUTH:8084"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true  # 允许cookie
            maxAge: 360000

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
